#!/bin/bash
if [ -z "$VERSION" ]; then 
    VERSION=`cat VERSION` 
fi
if [ -z "$DOCKERTAG" ]; then 
    DOCKERTAG="alpine-mini:$VERSION"
fi


docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
            --build-arg VCS_REF=`git rev-parse --short HEAD` \
            --build-arg VERSION=$VERSION \
            -t $DOCKERTAG .